/*
    Barkfield Road — Auto-Ship & Logistics
    Migration 001: initial schema
    Target: Azure SQL Database (SQL Server)

    Conventions
      - Surrogate keys are UNIQUEIDENTIFIER, generated by the application, never by the
        database. The domain's Create() factories assign ids, so NEWID() defaults would
        silently diverge from what the code inserted.
      - Enums are stored as TINYINT with CHECK constraints naming the valid values.
        Update the constraint whenever the matching C# enum gains a member.
      - Money is DECIMAL(10,2). Coordinates are DECIMAL(9,6).
      - Timestamps are DATETIME2(3) and always UTC. Pure calendar dates use DATE, and
        time-of-day windows use TIME(0).
      - Value objects are flattened: Address becomes Street, City, State, ZipCode;
        TimeWindow becomes a Start and an End column; GeoPoint becomes a Latitude
        and a Longitude column.
      - Cascades are used only inside an aggregate. Anything crossing an aggregate
        boundary is NO ACTION, both to preserve history and to avoid SQL Server's
        multiple-cascade-path restriction.
*/

-- Required for the filtered indexes below. sqlcmd does not default QUOTED_IDENTIFIER
-- to ON, and without these the CREATE INDEX statements fail with Msg 1934.
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
GO

/* ============================================================================
   IDENTITY
   ============================================================================ */

CREATE TABLE dbo.Users
(
    Id              UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_Users PRIMARY KEY,
    Name            NVARCHAR(200)       NOT NULL,
    Email           NVARCHAR(256)       NOT NULL,
    PasswordHash    NVARCHAR(256)       NOT NULL,
    IsActive        BIT                 NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT (1),

    -- Escape hatch honoured by the permission filter: an admin passes every check.
    IsAdmin         BIT                 NOT NULL CONSTRAINT DF_Users_IsAdmin DEFAULT (0),

    CreatedAt       DATETIME2(3)        NOT NULL,
    UpdatedAt       DATETIME2(3)        NULL
);
GO

CREATE UNIQUE INDEX UX_Users_Email ON dbo.Users (Email);
GO

CREATE TABLE dbo.Roles
(
    Id              UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_Roles PRIMARY KEY,
    Name            NVARCHAR(100)       NOT NULL,
    Description     NVARCHAR(400)       NOT NULL CONSTRAINT DF_Roles_Description DEFAULT (''),
    IsSystemRole    BIT                 NOT NULL CONSTRAINT DF_Roles_IsSystemRole DEFAULT (0),
    CreatedAt       DATETIME2(3)        NOT NULL,
    UpdatedAt       DATETIME2(3)        NULL
);
GO

CREATE UNIQUE INDEX UX_Roles_Name ON dbo.Roles (Name);
GO

/*  Permissions are internal reference data and are never addressed from outside the
    application, so they keep a small integer key. Roles use a GUID because role ids
    travel through the API on user create and edit. */
CREATE TABLE dbo.Permissions
(
    Id              INT                 NOT NULL IDENTITY(1,1) CONSTRAINT PK_Permissions PRIMARY KEY,
    Name            NVARCHAR(100)       NOT NULL,
    Description     NVARCHAR(400)       NOT NULL CONSTRAINT DF_Permissions_Description DEFAULT ('')
);
GO

CREATE UNIQUE INDEX UX_Permissions_Name ON dbo.Permissions (Name);
GO

CREATE TABLE dbo.RolePermissions
(
    RoleId          UNIQUEIDENTIFIER    NOT NULL,
    PermissionId    INT                 NOT NULL,

    CONSTRAINT PK_RolePermissions PRIMARY KEY (RoleId, PermissionId),
    CONSTRAINT FK_RolePermissions_Roles
        FOREIGN KEY (RoleId) REFERENCES dbo.Roles (Id) ON DELETE CASCADE,
    CONSTRAINT FK_RolePermissions_Permissions
        FOREIGN KEY (PermissionId) REFERENCES dbo.Permissions (Id) ON DELETE CASCADE
);
GO

CREATE TABLE dbo.UserRoles
(
    UserId          UNIQUEIDENTIFIER    NOT NULL,
    RoleId          UNIQUEIDENTIFIER    NOT NULL,

    CONSTRAINT PK_UserRoles PRIMARY KEY (UserId, RoleId),
    CONSTRAINT FK_UserRoles_Users
        FOREIGN KEY (UserId) REFERENCES dbo.Users (Id) ON DELETE CASCADE,
    CONSTRAINT FK_UserRoles_Roles
        FOREIGN KEY (RoleId) REFERENCES dbo.Roles (Id) ON DELETE CASCADE
);
GO

CREATE INDEX IX_UserRoles_RoleId ON dbo.UserRoles (RoleId);
GO

/*  Flattens user -> role -> permission for the authorization filter, which checks a
    permission name against a user id on every guarded request (cached 5 minutes). */
CREATE VIEW dbo.UserPermissions
AS
    SELECT DISTINCT
        ur.UserId,
        p.Name AS PermissionName
    FROM dbo.UserRoles           ur
    INNER JOIN dbo.RolePermissions rp ON rp.RoleId = ur.RoleId
    INNER JOIN dbo.Permissions     p  ON p.Id = rp.PermissionId;
GO

CREATE TABLE dbo.RefreshTokens
(
    Id                      INT             NOT NULL IDENTITY(1,1) CONSTRAINT PK_RefreshTokens PRIMARY KEY,
    UserId                  UNIQUEIDENTIFIER NOT NULL,

    -- SHA-256 of the raw token. The raw value is never stored.
    TokenHash               NVARCHAR(200)   NOT NULL,
    ExpiresAt               DATETIME2(3)    NOT NULL,
    CreatedAt               DATETIME2(3)    NOT NULL,
    CreatedByIp             NVARCHAR(64)    NULL,
    RevokedAt               DATETIME2(3)    NULL,
    RevokedByIp             NVARCHAR(64)    NULL,
    ReplacedByTokenHash     NVARCHAR(200)   NULL,
    ReasonRevoked           NVARCHAR(200)   NULL,

    CONSTRAINT FK_RefreshTokens_Users
        FOREIGN KEY (UserId) REFERENCES dbo.Users (Id) ON DELETE CASCADE
);
GO

CREATE UNIQUE INDEX UX_RefreshTokens_TokenHash ON dbo.RefreshTokens (TokenHash);
CREATE INDEX IX_RefreshTokens_UserId ON dbo.RefreshTokens (UserId);
GO

CREATE TABLE dbo.PasswordResetTokens
(
    Id              UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_PasswordResetTokens PRIMARY KEY,
    UserId          UNIQUEIDENTIFIER    NOT NULL,
    TokenHash       NVARCHAR(200)       NOT NULL,
    ExpiresAt       DATETIME2(3)        NOT NULL,
    IsUsed          BIT                 NOT NULL CONSTRAINT DF_PasswordResetTokens_IsUsed DEFAULT (0),
    CreatedAt       DATETIME2(3)        NOT NULL,
    UsedAt          DATETIME2(3)        NULL,

    CONSTRAINT FK_PasswordResetTokens_Users
        FOREIGN KEY (UserId) REFERENCES dbo.Users (Id) ON DELETE CASCADE
);
GO

CREATE INDEX IX_PasswordResetTokens_UserId ON dbo.PasswordResetTokens (UserId);
GO

/*  Written by ISqlExecutor.ExecuteWithAudit, inside the same transaction as the write
    it records, so the two roll back together. */
CREATE TABLE dbo.AuditLogs
(
    Id              BIGINT          NOT NULL IDENTITY(1,1) CONSTRAINT PK_AuditLogs PRIMARY KEY,
    Action          NVARCHAR(200)   NOT NULL,
    Query           NVARCHAR(MAX)   NULL,
    JsonParameters  NVARCHAR(MAX)   NULL,
    Timestamp       DATETIME2(3)    NOT NULL
);
GO

CREATE INDEX IX_AuditLogs_Timestamp ON dbo.AuditLogs (Timestamp DESC);
GO

/* ============================================================================
   CUSTOMERS
   ============================================================================ */

CREATE TABLE dbo.Customers
(
    Id                  UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_Customers PRIMARY KEY,

    -- Link to the Square customer profile. Null until provisioned.
    SquareCustomerId    NVARCHAR(128)       NULL,

    Email               NVARCHAR(256)       NOT NULL,
    FirstName           NVARCHAR(100)       NOT NULL,
    LastName            NVARCHAR(100)       NOT NULL,

    -- Digits only; the domain strips formatting on the way in.
    PhoneNumber         NVARCHAR(20)        NULL,
    Notes               NVARCHAR(MAX)       NULL,

    -- Address value object, flattened.
    Street              NVARCHAR(200)       NULL,
    City                NVARCHAR(100)       NULL,
    State               NVARCHAR(50)        NULL,
    ZipCode             NVARCHAR(20)        NULL,

    CreatedAt           DATETIME2(3)        NOT NULL,
    UpdatedAt           DATETIME2(3)        NULL
);
GO

CREATE INDEX IX_Customers_Email ON dbo.Customers (Email);
CREATE INDEX IX_Customers_LastName ON dbo.Customers (LastName, FirstName);
CREATE UNIQUE INDEX UX_Customers_SquareCustomerId
    ON dbo.Customers (SquareCustomerId) WHERE SquareCustomerId IS NOT NULL;
GO

CREATE TABLE dbo.Pets
(
    Id              UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_Pets PRIMARY KEY,
    CustomerId      UNIQUEIDENTIFIER    NOT NULL,
    Name            NVARCHAR(50)        NOT NULL,
    Birthday        DATE                NULL,

    -- PetType: 1 Dog, 2 Cat, 3 Other
    PetType         TINYINT             NOT NULL CONSTRAINT CK_Pets_PetType CHECK (PetType IN (1,2,3)),

    Breed           NVARCHAR(100)       NULL,
    Notes           NVARCHAR(MAX)       NULL,
    PictureUrl      NVARCHAR(500)       NULL,
    CreatedAt       DATETIME2(3)        NOT NULL,
    UpdatedAt       DATETIME2(3)        NULL,

    CONSTRAINT FK_Pets_Customers
        FOREIGN KEY (CustomerId) REFERENCES dbo.Customers (Id) ON DELETE CASCADE
);
GO

CREATE INDEX IX_Pets_CustomerId ON dbo.Pets (CustomerId);
GO

CREATE TABLE dbo.Allergies
(
    Id              UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_Allergies PRIMARY KEY,
    AllergyName     NVARCHAR(100)       NOT NULL
);
GO

CREATE UNIQUE INDEX UX_Allergies_AllergyName ON dbo.Allergies (AllergyName);
GO

CREATE TABLE dbo.PetAllergies
(
    PetId           UNIQUEIDENTIFIER    NOT NULL,
    AllergyId       UNIQUEIDENTIFIER    NOT NULL,

    CONSTRAINT PK_PetAllergies PRIMARY KEY (PetId, AllergyId),
    CONSTRAINT FK_PetAllergies_Pets
        FOREIGN KEY (PetId) REFERENCES dbo.Pets (Id) ON DELETE CASCADE,
    CONSTRAINT FK_PetAllergies_Allergies
        FOREIGN KEY (AllergyId) REFERENCES dbo.Allergies (Id)
);
GO

CREATE INDEX IX_PetAllergies_AllergyId ON dbo.PetAllergies (AllergyId);
GO

/*  Where a customer receives deliveries. Every column maps onto a field sent to the
    routing provider: address, instructions, duration and the time window. */
CREATE TABLE dbo.DeliveryLocations
(
    Id                      UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_DeliveryLocations PRIMARY KEY,
    CustomerId              UNIQUEIDENTIFIER    NOT NULL,
    Label                   NVARCHAR(100)       NOT NULL,

    Street                  NVARCHAR(200)       NOT NULL,
    City                    NVARCHAR(100)       NOT NULL,
    State                   NVARCHAR(50)        NOT NULL,
    ZipCode                 NVARCHAR(20)        NOT NULL,

    -- Optional. Routific geocodes from the address; these are stored only when a
    -- provider hands them back, and become required if routing comes in-house.
    Latitude                DECIMAL(9,6)        NULL,
    Longitude               DECIMAL(9,6)        NULL,

    -- Driver-facing: gate codes, "leave at side door", "dog in yard".
    AccessNotes             NVARCHAR(1000)      NULL,

    ServiceDurationMinutes  INT                 NOT NULL CONSTRAINT DF_DeliveryLocations_Duration DEFAULT (5),
    PreferredWindowStart    TIME(0)             NULL,
    PreferredWindowEnd      TIME(0)             NULL,

    IsDefault               BIT                 NOT NULL CONSTRAINT DF_DeliveryLocations_IsDefault DEFAULT (0),
    IsActive                BIT                 NOT NULL CONSTRAINT DF_DeliveryLocations_IsActive DEFAULT (1),
    CreatedAt               DATETIME2(3)        NOT NULL,
    UpdatedAt               DATETIME2(3)        NULL,

    CONSTRAINT FK_DeliveryLocations_Customers
        FOREIGN KEY (CustomerId) REFERENCES dbo.Customers (Id) ON DELETE CASCADE,
    CONSTRAINT CK_DeliveryLocations_Duration
        CHECK (ServiceDurationMinutes BETWEEN 0 AND 480),
    CONSTRAINT CK_DeliveryLocations_Window
        CHECK (PreferredWindowStart IS NULL OR PreferredWindowEnd IS NULL
               OR PreferredWindowEnd > PreferredWindowStart),
    CONSTRAINT CK_DeliveryLocations_Coordinates
        CHECK ((Latitude IS NULL AND Longitude IS NULL)
               OR (Latitude IS NOT NULL AND Longitude IS NOT NULL))
);
GO

CREATE INDEX IX_DeliveryLocations_CustomerId ON dbo.DeliveryLocations (CustomerId);

-- At most one default location per customer.
CREATE UNIQUE INDEX UX_DeliveryLocations_OneDefault
    ON dbo.DeliveryLocations (CustomerId) WHERE IsDefault = 1;
GO

/* ============================================================================
   CATALOG
   ============================================================================ */

/*  Catalog only, shared across every customer, mirrored from Square on demand.
    Quantity belongs to the line that references a product, never to the product. */
CREATE TABLE dbo.Products
(
    Id                      UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_Products PRIMARY KEY,
    SquareCatalogObjectId   NVARCHAR(128)       NOT NULL,
    Name                    NVARCHAR(200)       NOT NULL,
    Sku                     NVARCHAR(100)       NULL,
    Price                   DECIMAL(10,2)       NOT NULL CONSTRAINT CK_Products_Price CHECK (Price >= 0),
    IsActive                BIT                 NOT NULL CONSTRAINT DF_Products_IsActive DEFAULT (1),
    CreatedAt               DATETIME2(3)        NOT NULL,
    UpdatedAt               DATETIME2(3)        NULL
);
GO

CREATE UNIQUE INDEX UX_Products_SquareCatalogObjectId ON dbo.Products (SquareCatalogObjectId);
CREATE INDEX IX_Products_Name ON dbo.Products (Name) WHERE IsActive = 1;
GO

/* ============================================================================
   SUBSCRIPTIONS
   ============================================================================ */

CREATE TABLE dbo.Subscriptions
(
    Id                  UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_Subscriptions PRIMARY KEY,
    CustomerId          UNIQUEIDENTIFIER    NOT NULL,

    -- SubscriptionStatus: 1 NewSignUp, 2 Active, 3 Paused, 4 Canceled
    Status              TINYINT             NOT NULL
        CONSTRAINT CK_Subscriptions_Status CHECK (Status IN (1,2,3,4)),

    -- OrderFrequency value object, flattened. FrequencyUnit: 1 Days, 2 Weeks, 3 Months
    FrequencyInterval   INT                 NOT NULL
        CONSTRAINT CK_Subscriptions_Interval CHECK (FrequencyInterval > 0),
    FrequencyUnit       TINYINT             NOT NULL
        CONSTRAINT CK_Subscriptions_Unit CHECK (FrequencyUnit IN (1,2,3)),

    -- FulfillmentMethod: 1 LocalDelivery, 2 Pickup, 3 Shipping
    FulfillmentMethod   TINYINT             NOT NULL
        CONSTRAINT CK_Subscriptions_Fulfillment CHECK (FulfillmentMethod IN (1,2,3)),

    NextDeliveryDate    DATE                NOT NULL,
    LastDeliveryDate    DATE                NULL,
    SignUpDate          DATETIME2(3)        NOT NULL,
    CreatedAt           DATETIME2(3)        NOT NULL,
    UpdatedAt           DATETIME2(3)        NULL,

    CONSTRAINT FK_Subscriptions_Customers
        FOREIGN KEY (CustomerId) REFERENCES dbo.Customers (Id) ON DELETE CASCADE
);
GO

CREATE INDEX IX_Subscriptions_CustomerId ON dbo.Subscriptions (CustomerId);

-- Drives the job that generates upcoming deliveries.
CREATE INDEX IX_Subscriptions_Due ON dbo.Subscriptions (NextDeliveryDate, Status);
GO

/*  Static lines: this product, this quantity, every delivery. */
CREATE TABLE dbo.SubscriptionItems
(
    Id              UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_SubscriptionItems PRIMARY KEY,
    SubscriptionId  UNIQUEIDENTIFIER    NOT NULL,
    ProductId       UNIQUEIDENTIFIER    NOT NULL,
    Quantity        INT                 NOT NULL
        CONSTRAINT CK_SubscriptionItems_Quantity CHECK (Quantity > 0),
    CreatedAt       DATETIME2(3)        NOT NULL,
    UpdatedAt       DATETIME2(3)        NULL,

    CONSTRAINT FK_SubscriptionItems_Subscriptions
        FOREIGN KEY (SubscriptionId) REFERENCES dbo.Subscriptions (Id) ON DELETE CASCADE,
    CONSTRAINT FK_SubscriptionItems_Products
        FOREIGN KEY (ProductId) REFERENCES dbo.Products (Id)
);
GO

-- The domain raises the quantity rather than adding a duplicate line.
CREATE UNIQUE INDEX UX_SubscriptionItems_Product
    ON dbo.SubscriptionItems (SubscriptionId, ProductId);
CREATE INDEX IX_SubscriptionItems_ProductId ON dbo.SubscriptionItems (ProductId);
GO

/*  An ordered set of products where exactly one ships per delivery.
    RotationPosition is a monotonic counter; the current pick is
    ItemsInSequence[RotationPosition % Count]. Using modulo of an ever-increasing
    counter means the cursor cannot fall out of range when staff edit the group. */
CREATE TABLE dbo.RotationGroups
(
    Id                  UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_RotationGroups PRIMARY KEY,
    SubscriptionId      UNIQUEIDENTIFIER    NOT NULL,
    Name                NVARCHAR(100)       NOT NULL,
    RotationPosition    INT                 NOT NULL CONSTRAINT DF_RotationGroups_Position DEFAULT (0),
    IsActive            BIT                 NOT NULL CONSTRAINT DF_RotationGroups_IsActive DEFAULT (1),
    CreatedAt           DATETIME2(3)        NOT NULL,
    UpdatedAt           DATETIME2(3)        NULL,

    CONSTRAINT FK_RotationGroups_Subscriptions
        FOREIGN KEY (SubscriptionId) REFERENCES dbo.Subscriptions (Id) ON DELETE CASCADE,
    CONSTRAINT CK_RotationGroups_Position CHECK (RotationPosition >= 0)
);
GO

CREATE INDEX IX_RotationGroups_SubscriptionId ON dbo.RotationGroups (SubscriptionId);
CREATE UNIQUE INDEX UX_RotationGroups_Name ON dbo.RotationGroups (SubscriptionId, Name);
GO

CREATE TABLE dbo.RotationGroupItems
(
    Id                  UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_RotationGroupItems PRIMARY KEY,
    RotationGroupId     UNIQUEIDENTIFIER    NOT NULL,
    ProductId           UNIQUEIDENTIFIER    NOT NULL,

    -- 1-based, kept contiguous by the owning group.
    SequenceOrder       INT                 NOT NULL,
    Quantity            INT                 NOT NULL
        CONSTRAINT CK_RotationGroupItems_Quantity CHECK (Quantity > 0),
    CreatedAt           DATETIME2(3)        NOT NULL,
    UpdatedAt           DATETIME2(3)        NULL,

    CONSTRAINT FK_RotationGroupItems_RotationGroups
        FOREIGN KEY (RotationGroupId) REFERENCES dbo.RotationGroups (Id) ON DELETE CASCADE,
    CONSTRAINT FK_RotationGroupItems_Products
        FOREIGN KEY (ProductId) REFERENCES dbo.Products (Id)
);
GO

CREATE UNIQUE INDEX UX_RotationGroupItems_Product
    ON dbo.RotationGroupItems (RotationGroupId, ProductId);
CREATE INDEX IX_RotationGroupItems_ProductId ON dbo.RotationGroupItems (ProductId);
GO

/*  One-off items attached to the next delivery only. There is deliberately no target
    date: pending means ConsumedAt IS NULL, so rescheduling cannot orphan an add-on.
    Consumed rows are retained as delivery history rather than deleted. */
CREATE TABLE dbo.SubscriptionAddOns
(
    Id              UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_SubscriptionAddOns PRIMARY KEY,
    SubscriptionId  UNIQUEIDENTIFIER    NOT NULL,
    ProductId       UNIQUEIDENTIFIER    NOT NULL,
    Quantity        INT                 NOT NULL
        CONSTRAINT CK_SubscriptionAddOns_Quantity CHECK (Quantity > 0),
    Note            NVARCHAR(500)       NULL,
    CreatedAt       DATETIME2(3)        NOT NULL,
    ConsumedAt      DATETIME2(3)        NULL,

    CONSTRAINT FK_SubscriptionAddOns_Subscriptions
        FOREIGN KEY (SubscriptionId) REFERENCES dbo.Subscriptions (Id) ON DELETE CASCADE,
    CONSTRAINT FK_SubscriptionAddOns_Products
        FOREIGN KEY (ProductId) REFERENCES dbo.Products (Id)
);
GO

-- Pending add-ons are the hot read when building a manifest.
CREATE INDEX IX_SubscriptionAddOns_Pending
    ON dbo.SubscriptionAddOns (SubscriptionId) WHERE ConsumedAt IS NULL;
CREATE INDEX IX_SubscriptionAddOns_ProductId ON dbo.SubscriptionAddOns (ProductId);
GO

/* ============================================================================
   DELIVERIES
   ============================================================================ */

CREATE TABLE dbo.Deliveries
(
    Id                              UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_Deliveries PRIMARY KEY,
    SubscriptionId                  UNIQUEIDENTIFIER    NOT NULL,
    CustomerId                      UNIQUEIDENTIFIER    NOT NULL,

    ScheduledFor                    DATE                NOT NULL,
    CompletedAt                     DATETIME2(3)        NULL,

    -- DeliveryStatus: 1 Scheduled, 2 Packed, 3 Routed, 4 OutForDelivery,
    --                 5 Delivered, 6 Failed, 7 Canceled
    Status                          TINYINT             NOT NULL
        CONSTRAINT CK_Deliveries_Status CHECK (Status IN (1,2,3,4,5,6,7)),

    -- FulfillmentMethod: 1 LocalDelivery, 2 Pickup, 3 Shipping
    FulfillmentMethod               TINYINT             NOT NULL
        CONSTRAINT CK_Deliveries_Fulfillment CHECK (FulfillmentMethod IN (1,2,3)),

    -- ProcurementStatus: 1 NotStarted, 2 InProgress, 3 Blocked, 4 Ready.
    -- Derived from the lines, recomputed inside the aggregate on every line change,
    -- and persisted so the packing worklist can filter on it in SQL.
    ProcurementStatus               TINYINT             NOT NULL
        CONSTRAINT CK_Deliveries_Procurement CHECK (ProcurementStatus IN (1,2,3,4)),

    HasPaid                         BIT                 NOT NULL CONSTRAINT DF_Deliveries_HasPaid DEFAULT (0),
    AstroCompleted                  BIT                 NOT NULL CONSTRAINT DF_Deliveries_Astro DEFAULT (0),

    -- Routing provider's order id. Our own Id is sent as their customer order number,
    -- so it round-trips on every webhook; this is for calls back to them.
    ExternalOrderId                 NVARCHAR(128)       NULL,
    SentToRoutingAt                 DATETIME2(3)        NULL,

    DeliveryLocationId              UNIQUEIDENTIFIER    NOT NULL,

    -- Address snapshotted at scheduling time, so a customer moving house never
    -- rewrites where a past delivery went.
    DeliveryStreet                  NVARCHAR(200)       NOT NULL,
    DeliveryCity                    NVARCHAR(100)       NOT NULL,
    DeliveryState                   NVARCHAR(50)        NOT NULL,
    DeliveryZipCode                 NVARCHAR(20)        NOT NULL,
    DeliveryLatitude                DECIMAL(9,6)        NULL,
    DeliveryLongitude               DECIMAL(9,6)        NULL,

    RequestedWindowStart            TIME(0)             NULL,
    RequestedWindowEnd              TIME(0)             NULL,
    ServiceDurationMinutesOverride  INT                 NULL,

    Notes                           NVARCHAR(MAX)       NULL,
    FailureReason                   NVARCHAR(500)       NULL,

    CreatedAt                       DATETIME2(3)        NOT NULL,
    UpdatedAt                       DATETIME2(3)        NULL,

    CONSTRAINT FK_Deliveries_Subscriptions
        FOREIGN KEY (SubscriptionId) REFERENCES dbo.Subscriptions (Id),
    CONSTRAINT FK_Deliveries_Customers
        FOREIGN KEY (CustomerId) REFERENCES dbo.Customers (Id),
    CONSTRAINT FK_Deliveries_DeliveryLocations
        FOREIGN KEY (DeliveryLocationId) REFERENCES dbo.DeliveryLocations (Id),
    CONSTRAINT CK_Deliveries_Window
        CHECK (RequestedWindowStart IS NULL OR RequestedWindowEnd IS NULL
               OR RequestedWindowEnd > RequestedWindowStart)
);
GO

-- The dispatch screen: everything due on a date, by workflow state.
CREATE INDEX IX_Deliveries_Scheduled ON dbo.Deliveries (ScheduledFor, Status);

-- The packing worklist, especially "show me everything blocked".
CREATE INDEX IX_Deliveries_Procurement ON dbo.Deliveries (ScheduledFor, ProcurementStatus);

CREATE INDEX IX_Deliveries_SubscriptionId ON dbo.Deliveries (SubscriptionId);
CREATE INDEX IX_Deliveries_CustomerId ON dbo.Deliveries (CustomerId, ScheduledFor DESC);

-- Webhook lookups arrive by the provider's order id.
CREATE UNIQUE INDEX UX_Deliveries_ExternalOrderId
    ON dbo.Deliveries (ExternalOrderId) WHERE ExternalOrderId IS NOT NULL;
GO

/*  Name and unit price are snapshotted at scheduling time, so renaming or repricing a
    catalog product never rewrites what a past delivery shipped and charged. */
CREATE TABLE dbo.DeliveryLines
(
    Id                          UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_DeliveryLines PRIMARY KEY,
    DeliveryId                  UNIQUEIDENTIFIER    NOT NULL,
    ProductId                   UNIQUEIDENTIFIER    NOT NULL,

    ProductName                 NVARCHAR(200)       NOT NULL,
    UnitPrice                   DECIMAL(10,2)       NOT NULL,
    Quantity                    INT                 NOT NULL
        CONSTRAINT CK_DeliveryLines_Quantity CHECK (Quantity > 0),

    -- DeliveryLineSource: 1 Recurring, 2 Rotation, 3 AddOn
    Source                      TINYINT             NOT NULL
        CONSTRAINT CK_DeliveryLines_Source CHECK (Source IN (1,2,3)),

    -- The SubscriptionItem, RotationGroup or SubscriptionAddOn this line came from.
    -- Intentionally not a foreign key: it points at three different tables, and the
    -- source row may be edited or removed long after the delivery is history.
    SourceId                    UNIQUEIDENTIFIER    NOT NULL,

    -- LineOrderStatus: 1 Pending, 2 Ordered, 3 PartiallyReceived, 4 Received,
    --                  5 OutOfStock, 6 Substituted, 7 Shorted
    OrderStatus                 TINYINT             NOT NULL
        CONSTRAINT CK_DeliveryLines_OrderStatus CHECK (OrderStatus IN (1,2,3,4,5,6,7)),

    QuantityReceived            INT                 NOT NULL CONSTRAINT DF_DeliveryLines_QtyReceived DEFAULT (0),

    SubstitutedWithProductId    UNIQUEIDENTIFIER    NULL,
    SubstitutedWithProductName  NVARCHAR(200)       NULL,
    SubstitutedWithUnitPrice    DECIMAL(10,2)       NULL,

    StatusNote                  NVARCHAR(500)       NULL,
    StatusUpdatedAt             DATETIME2(3)        NULL,

    CONSTRAINT FK_DeliveryLines_Deliveries
        FOREIGN KEY (DeliveryId) REFERENCES dbo.Deliveries (Id) ON DELETE CASCADE,
    CONSTRAINT FK_DeliveryLines_Products
        FOREIGN KEY (ProductId) REFERENCES dbo.Products (Id),
    CONSTRAINT FK_DeliveryLines_SubstituteProducts
        FOREIGN KEY (SubstitutedWithProductId) REFERENCES dbo.Products (Id),
    CONSTRAINT CK_DeliveryLines_QuantityReceived CHECK (QuantityReceived >= 0),
    CONSTRAINT CK_DeliveryLines_Substitution
        CHECK (OrderStatus <> 6 OR SubstitutedWithProductId IS NOT NULL)
);
GO

CREATE INDEX IX_DeliveryLines_DeliveryId ON dbo.DeliveryLines (DeliveryId);
CREATE INDEX IX_DeliveryLines_ProductId ON dbo.DeliveryLines (ProductId);

-- "What is outstanding across the whole week" on the purchasing screen.
CREATE INDEX IX_DeliveryLines_Unresolved
    ON dbo.DeliveryLines (OrderStatus, ProductId) WHERE OrderStatus IN (1,2,3,5);
GO

/* ============================================================================
   ROUTING
   ============================================================================ */

/*  Routes are built in the routing provider and arrive here already published, via the
    route.published webhook. Nothing in this system creates one. */
CREATE TABLE dbo.Routes
(
    Id                  UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_Routes PRIMARY KEY,

    -- The provider's route id. Correlation key for republishes.
    ExternalRouteId     NVARCHAR(128)       NOT NULL,

    ScheduledDate       DATE                NOT NULL,
    Name                NVARCHAR(200)       NOT NULL,

    -- RouteStatus: 1 Planned, 2 Published, 3 Executing, 4 Completed, 5 Canceled
    Status              TINYINT             NOT NULL
        CONSTRAINT CK_Routes_Status CHECK (Status IN (1,2,3,4,5)),

    -- Driver as named by the provider. Drivers are not local users in this phase.
    DriverName          NVARCHAR(200)       NULL,
    DriverEmail         NVARCHAR(256)       NULL,

    WorkingTimeSeconds  INT                 NULL,
    DistanceKilometers  DECIMAL(9,3)        NULL,

    PublishedAt         DATETIME2(3)        NOT NULL,
    ReceivedAt          DATETIME2(3)        NOT NULL,
    UpdatedAt           DATETIME2(3)        NULL
);
GO

CREATE UNIQUE INDEX UX_Routes_ExternalRouteId ON dbo.Routes (ExternalRouteId);
CREATE INDEX IX_Routes_ScheduledDate ON dbo.Routes (ScheduledDate, Status);
GO

/*  Carries no delivery outcome. Delivered or failed lives on Deliveries, so the two
    can never disagree. LoadedAt is ours and survives a republish. */
CREATE TABLE dbo.RouteStops
(
    Id                      UNIQUEIDENTIFIER    NOT NULL CONSTRAINT PK_RouteStops PRIMARY KEY,
    RouteId                 UNIQUEIDENTIFIER    NOT NULL,
    DeliveryId              UNIQUEIDENTIFIER    NOT NULL,

    SequenceOrder           INT                 NOT NULL,
    ExternalStopId          NVARCHAR(128)       NULL,

    PlannedArrival          TIME(0)             NULL,
    PlannedDeparture        TIME(0)             NULL,
    ActualArrival           TIME(0)             NULL,
    ActualDeparture         TIME(0)             NULL,
    DistanceFromPreviousKm  DECIMAL(9,3)        NULL,

    LoadedAt                DATETIME2(3)        NULL,
    CreatedAt               DATETIME2(3)        NOT NULL,
    UpdatedAt               DATETIME2(3)        NULL,

    CONSTRAINT FK_RouteStops_Routes
        FOREIGN KEY (RouteId) REFERENCES dbo.Routes (Id) ON DELETE CASCADE,
    CONSTRAINT FK_RouteStops_Deliveries
        FOREIGN KEY (DeliveryId) REFERENCES dbo.Deliveries (Id)
);
GO

CREATE UNIQUE INDEX UX_RouteStops_Delivery ON dbo.RouteStops (RouteId, DeliveryId);
CREATE INDEX IX_RouteStops_RouteId ON dbo.RouteStops (RouteId, SequenceOrder);
CREATE INDEX IX_RouteStops_DeliveryId ON dbo.RouteStops (DeliveryId);
GO

/* ============================================================================
   WEBHOOK IDEMPOTENCY

   The routing provider retries any webhook it does not get a 200 for, and events can
   arrive out of order. Every handler records the provider's event id here first and
   skips anything already present.
   ============================================================================ */

CREATE TABLE dbo.WebhookEvents
(
    EventId         NVARCHAR(200)   NOT NULL CONSTRAINT PK_WebhookEvents PRIMARY KEY,
    Provider        NVARCHAR(50)    NOT NULL,
    Topic           NVARCHAR(100)   NOT NULL,
    ReceivedAt      DATETIME2(3)    NOT NULL,
    ProcessedAt     DATETIME2(3)    NULL,
    Payload         NVARCHAR(MAX)   NULL,
    ProcessingError NVARCHAR(MAX)   NULL
);
GO

CREATE INDEX IX_WebhookEvents_ReceivedAt ON dbo.WebhookEvents (ReceivedAt DESC);
CREATE INDEX IX_WebhookEvents_Unprocessed
    ON dbo.WebhookEvents (Topic, ReceivedAt) WHERE ProcessedAt IS NULL;
GO
